repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.0.1"
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v6.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: "v0.4.0"
    hooks:
      - id: markdownlint-cli2

  - repo: https://github.com/frnmst/md-toc
    rev: "8.1.1"
    hooks:
      - id: md-toc
        args: [-p, -s, "1", github]

exclude: |
  (?x)(
    ^CHANGELOG.md$
  )
