- name: "{{ asdf_plugin_name }} : Add plugin"
  ansible.builtin.command: >-
    asdf plugin add {{ asdf_plugin_name }} {{ asdf_plugin_git_url }}
  register: task
  failed_when: task.rc >= 1 and 'already added' not in task.stderr
  changed_when: task.rc == 0

- name: "{{ asdf_plugin_name }} : Checkout plugin repo at ref"
  when: asdf_plugin_git_ref is defined
  ansible.builtin.command: >-
    asdf plugin update {{ asdf_plugin_name }} {{ asdf_plugin_git_ref }}
  register: task
  failed_when: task.rc > 0 or 'fatal' in task.stdout or 'error' in task.stdout
  changed_when: false

- name: "{{ asdf_plugin_name }} : Install package {{ asdf_plugin_package_versions | default('SKIP') }}"
  when: asdf_plugin_package_versions is defined
  ansible.builtin.command: >-
    asdf install {{ asdf_plugin_name }} {{ item }}
  loop: "{{ asdf_plugin_package_versions }}"
  register: task
  failed_when: task.rc > 0
  changed_when: false

- name: "{{ asdf_plugin_name }} : Set the global version to {{ asdf_plugin_package_version_global | default('SKIP') }}"
  when: asdf_plugin_package_version_global is defined
  ansible.builtin.command: >-
    asdf global {{ asdf_plugin_name }} {{ asdf_plugin_package_version_global }}
  register: task
  failed_when: task.rc > 0
  changed_when: false
