# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: primary

'on':
  workflow_dispatch:
  push:
    branches: [trunk]

jobs:
  primary:
    runs-on: ubuntu-latest

    steps:
      # ------------------------------------------------------------------------

      - uses: actions/checkout@v3

      # ------------------------------------------------------------------------
      # Pre-Commit

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Setup pre-commit
        run: |
          pip install pre-commit
          pre-commit install

      - name: Cache pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit

      - run: pre-commit run --all-files --verbose --show-diff-on-failure

      # ------------------------------------------------------------------------
      # Semantic Release

      - name: Copy package meta info to root
        run: |
          cp node/package* .

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm

      - name: Install packages
        run: npm install --no-progress --prefer-offline --no-audit

      - name: Semantic Release
        run: npx --no-install semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ------------------------------------------------------------------------
      # Ansible Galaxy

      - name: Import to Ansible Galaxy
        uses: robertdebock/galaxy-action@1.2.1
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
          git_branch: trunk

      # ------------------------------------------------------------------------
